services:
    db:
        container_name: 1m25_12-db
        hostname: $NS_MARIADB_HOSTNAME
        image: mariadb:12.0.2-noble
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: $NS_MARIADB_DATABASE
            MYSQL_PORT: $NS_MARIADB_PORT
            MYSQL_USER: $NS_MARIADB_USER
            MYSQL_PASSWORD: $NS_MARIADB_PASSWORD
            MYSQL_ROOT_PASSWORD: password
        env_file:
          - .env
          - .env.development
        ports:
            - "3306:3306"

volumes:
    db:
