services:
    db:
        container_name: 1m25_12-db
        hostname: $NS_MARIADB_HOSTNAME
        image: mariadb:12.0.2-noble
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: $NS_MARIADB_DATABASE
            MYSQL_PORT: $NS_MARIADB_PORT
            MYSQL_USER: $NS_MARIADB_USER
            MYSQL_PASSWORD: $NS_MARIADB_PASSWORD
            MYSQL_ROOT_PASSWORD: password
        env_file:
          - .env
          - .env.development
        ports:
            - "3306:3306"
        healthcheck:
            test:
                [
                    "CMD",
                    "mariadb-admin",
                    "-h",
                    "$NS_MARIADB_HOSTNAME",
                    "-P",
                    "$NS_MARIADB_PORT",
                    "-u",
                    "$NS_MARIADB_USER",
                    "-p$NS_MARIADB_PASSWORD",
                    "ping",
                ]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 1s

    adminer:
        image: adminer:latest
        ports:
            - "8081:8080"
        depends_on:
            db:
                condition: service_healthy

volumes:
    db:
