FROM node:24.5-alpine

WORKDIR /app

ENV NODE_ENV=development

RUN npm install -g pnpm

COPY ./package.json ./pnpm-lock.yaml .
RUN pnpm i --frozen-lockfile

COPY ./prisma/schema.prisma ./prisma/
RUN npx prisma generate

EXPOSE 3000
